### PR TITLE
Exposing `ERROR` log level

### PR DESCRIPTION
**Pull request by vkruoso**
This aims to add support for the `ERROR` log level on the background logger.

### CODE REVIEW

**Comment by vkruoso** [comment]
@jussimalinen can you take a look at this PR?

**Comment by pekkaklarck** [comment]
Thanks!

**Comment by vkruoso** [comment]
@pekkaklarck Do you think we can release a new version of this module? It seems that it have little changes, and publishing it would allow me to remove the fix from the codebase.

**Comment by pekkaklarck** [comment]
Sure. The main blocker is that I'm currently on holiday with a limited free time for coding and I should actually make Se2Lib release ASAP too. I'd also like to make sure this code is Python 3 compatible before the next release. Do you @vkruoso have a possibility to test that?

**Comment by vkruoso** [comment]
I can try. My experience with Python 3 is really limited. Would you like to have the tests here improved for py3 or running some compatibility tools is enough?

**Comment by pekkaklarck** [comment]
It ought to be enough if test pass with Py3. I don't think new tests are needed, but existing may need to be adjusted to be Py3 compatible.

I doubt this is a big task and if we are lucky the code may even work without changes. I'm happy to help if you encounter problems. Could you start by submitting an issue about Py3? We can continue discussion there instead in the comments of this unrelated PR.

**Comment by vkruoso** [comment]
Great. Will create the issue and try to work on it as soon as possible.

**Pull request merged**
